### ISSUE TITLE
Some entries do not trigger

### ISSUE THREAD

**Issue by tobi-nmx** [ioBroker/ioBroker.fullcalendar#122]
**Describe the bug**  
Some entries in the calendar just don't trigger. Same applies for copies of the noin-triggering events. When moving these event e.g 5 minutes after current time, debug log says "Next check in 3600 seconds". 

**To Reproduce**  
1. Create event
2. Wait for event to trigger
3. Notice that it didn't

**Expected behavior**  
All events in the calendar should trigger (and throw an error message if something fails)

**Screenshots & Logfiles**  
--

**Versions:**  
 - Adapter version: v2.2.6
 - JS-Controller version: v5.0.12
 - Node version: v18.17.1
 - Operating system: Docker

**Additional context**  
I can exactly replicate an entry and it works. Is there any way I can see and compare triggering and non-triggering entries in a raw format (e.g. on database/config level)?

**Comment by martini-69-k** [comment]
Hi, same problem for me!
In the past i triggered a scene-object at. 5:45 AM with no problems.
Since an update of fullcalendar, don't know which one I had before, the same trigger has problems to be executed.
Others still work but are executed at a different time.
The problem ist not the scene-object. If I change the time at when to has been executed ist works!
This is not a big issue but is worth to think about.
Thanks for this great adapter for iobroker!!! :-)

LG
Martin

**Comment by GermanBluefox** [comment]
Please retest with 2.3.2

**Comment by tobi-nmx** [comment]
Seems to work with 2.3.3. Have you found the issue (this was about daily events, not monthly)?
